# Generated by Django 5.0.6 on 2024-05-26 00:45

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('sub_title', models.CharField(blank=True, max_length=400, null=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/book')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('pre_order', models.BooleanField(default=False)),
                ('is_home_scroll', models.BooleanField(default=False)),
                ('is_new_released', models.BooleanField(default=False)),
                ('amazon_url', models.CharField(blank=True, max_length=400, null=True)),
                ('apple_url', models.CharField(blank=True, max_length=400, null=True)),
                ('barnes_url', models.CharField(blank=True, max_length=400, null=True)),
                ('kobo_url', models.CharField(blank=True, max_length=400, null=True)),
                ('buy_now_url', models.CharField(blank=True, max_length=400, null=True)),
                ('free_download_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=400, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('available_in', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('tags', models.ManyToManyField(to='book.tag')),
            ],
        ),
        migrations.CreateModel(
            name='BookGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/books')),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'verbose_name': 'bookgallery',
                'verbose_name_plural': 'book gallery',
            },
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField(blank=True)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
