# Generated by Django 5.0.6 on 2024-05-26 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('source_url', models.CharField(max_length=500)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('available', models.BooleanField(default=True)),
                ('feature', models.BooleanField(default=False)),
                ('image', models.ImageField(null=True, upload_to='posts')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
